import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import estilos from "@/styles/Home.module.css";
import Topo from "../componentes/Topo"
import SecaoCapa from "../componentes/SecaoCapa"
import SecaoProdutos from "../componentes/SecaoProdutos";
import SecaoSobre from "../componentes/SecaoSobre";
import SecaoContatos from "../componentes/SecaoContatos";
import Rodape from "../componentes/Rodape";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
      <Topo/>
      </header>
      <main>
        <SecaoCapa/>
        <SecaoProdutos/>
        <SecaoSobre/>
        <SecaoContatos/>
      </main>
      <footer>
        <Rodape/>
      </footer>
    </>
  );
}
